title: lsp-dart
description: Emacs Dart IDE using lsp-mode to connect to Dart Analysis Server.
logo: https://raw.githubusercontent.com/emacs-lsp/lsp-mode/master/examples/logo.png

theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs

# just-the-docs configs
color_scheme: "nil"
aux_links:
  "Github":
    - "//github.com/emacs-lsp/lsp-dart"
  "lsp-mode":
    - "//github.com/emacs-lsp/lsp-mode"

footer_content: "Copyright &copy; 2020 emacs-lsp. Distributed by an <a href=\"https://github.com/emacs-lsp/lsp-dart/tree/master/LICENSE\">GNU GPL license.</a>"
