site_name: LSP Dart

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: images/logo.svg
  favicon: images/logo.svg
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/emacs-lsp
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yonchovski

repo_name: emacs-lsp/lsp-dart
repo_url: https://github.com/emacs-lsp/lsp-dart

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - codehilite
  - toc:
      permalink: '#'

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized

nav:
